### ISSUE TITLE
Hello very nice App but there is a bug

### ISSUE THREAD

**Issue by frankyxcs** [lamrak/My_Fishing_Diary#1]
Hi !! 

Just installed the app ...its very nice but i have found a bug :+1: 

it is not possible to Edit an entry and also deleting crashes the app. I think you forgot to implement an update method and while deleting the entry the app crashes too

FATAL EXCEPTION: main
Process: net.validcat.fishing, PID: 2704
                                                                    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: fishing.place (code 2067)
                                                                        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
                                                                        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                                        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                                        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
                                                                        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
                                                                        at net.validcat.fishing.data.FishingProvider.update(FishingProvider.java:322)
                                                                        at android.content.ContentProvider$Transport.update(ContentProvider.java:355)
                                                                        at android.content.ContentResolver.update(ContentResolver.java:1367)
                                                                        at net.validcat.fishing.fragments.AddNewFishingFragment.storeNewFishing(AddNewFishingFragment.java:225)
                                                                        at net.validcat.fishing.fragments.AddNewFishingFragment.onOptionsItemSelected(AddNewFishingFragment.java:173)

would be nice if you can fix these problems if you have time !

thanx frank

**Comment by lamrak** [comment]
Hi! Thank you, we will check this issue and will fix it.

**Comment by frankyxcs** [comment]
hi ok ! 

also deleting an entry the app crashes here  

Deleting an entry: the app crashes here

FragmentManager manager = getSupportFragmentManager();
FragmentManager.BackStackEntry backEntry = getSupportFragmentManager().getBackStackEntryAt(this.getSupportFragmentManager().getBackStackEntryCount() - 1);
if (backEntry !=null) {
    String str = backEntry.getName();
    Fragment df = getSupportFragmentManager().findFragmentByTag(str);
    FragmentTransaction trans = manager.beginTransaction();
    trans.remove(df);
    trans.commit();
    manager.popBackStack();

**Comment by lamrak** [comment]
Hi, this issue already fixed. Thank you :)
